dist: trusty
sudo: false
language: cpp


before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - pip install --user cpp-coveralls

script:
  - cmake -DCOVERAGE=1 .
  - cmake --build .
  - ./tests

after_success:
  - coveralls --root . -E ".*extern.*" -E ".*CMakeFiles.*"