dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

git:
  submodules: false

before_install:
  - eval "${MATRIX_EVAL}"
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=1 ..
  - cmake --build . --target tests
  - ./tests

after_success:
  - coveralls --root . --include src/*.cpp --include include/*.hpp -E ".*extern.*" -E ".*CMakeFiles.*"