dist: trusty
sudo: false
language: cpp

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=1 ..
  - cmake --build . --target tests
  - ./tests

after_success:
  - coveralls --root . -E ".*extern.*" -E ".*CMakeFiles.*"